fix: default name for job docker container
equinor/dm-job pull request #83
Opened 2023-10-18 14:41 UTC by collinlokken

## What does this pull request change?
Default name for jobs that run local containers because name is an optional attribute in the Job blueprint

## Why is this pull request needed?
Makes sure that the job handler does not crash if the job entity does not have a name

## Issues related to this change

2023-10-18 19:30 UTC, henrikbossart submitted a review, later dismissed

2023-10-19 06:40 UTC, soofstad requested changes, later dismissed

2023-10-19 06:40 UTC, soofstad commented on src/job_handler_plugins/local_container/__init__.py
> +            name=self.job.entity.get("name", "local-job"),
So as we discussed, should be possible to run multiple jobs simultaneously.
So adding a short 5-8 char random suffix would help.

2023-10-19 06:40 UTC, soofstad commented on src/job_handler_plugins/local_container/__init__.py
> +            container = self.client.containers.get(self.job.entity.get("name", "local-job"))
If the containers name is generated, you will need to set that in the entity when starting the job. And if it's not there. remove() must fail.

2023-10-19 12:14 UTC, eoaksnes approved these changes

2023-10-19 12:14 UTC, eoaksnes commented on src/job_handler_plugins/local_container/__init__.py
> +        self.local_container_name = job.entity.get("name", container_name(10))
Suggestion: Change container_name to autogenerate_container_name.

2023-10-19 12:31 UTC, merged